olympics_medals = [
    {"country": "United States", "total_medals": 113, "gold": 39, "silver": 41, "bronze": 33},
    {"country": "China", "total_medals": 88, "gold": 38, "silver": 32, "bronze": 18},
    {"country": "Japan", "total_medals": 58, "gold": 27, "silver": 14, "bronze": 17},
    {"country": "Great Britain", "total_medals": 65, "gold": 22, "silver": 21, "bronze": 22},
    {"country": "ROC (Russia)", "total_medals": 71, "gold": 20, "silver": 28, "bronze": 23},
    {"country": "Australia", "total_medals": 46, "gold": 17, "silver": 7, "bronze": 22},
    {"country": "Netherlands", "total_medals": 36, "gold": 10, "silver": 12, "bronze": 14},
    {"country": "France", "total_medals": 33, "gold": 10, "silver": 12, "bronze": 11},
    {"country": "Germany", "total_medals": 37, "gold": 10, "silver": 11, "bronze": 16},
    {"country": "Italy", "total_medals": 40, "gold": 10, "silver": 10, "bronze": 20},
    {"country": "Canada", "total_medals": 24, "gold": 7, "silver": 6, "bronze": 11},
    {"country": "Brazil", "total_medals": 21, "gold": 7, "silver": 6, "bronze": 8},
    {"country": "New Zealand", "total_medals": 20, "gold": 7, "silver": 6, "bronze": 7},
    {"country": "Cuba", "total_medals": 15, "gold": 7, "silver": 3, "bronze": 5},
    {"country": "Hungary", "total_medals": 20, "gold": 6, "silver": 7, "bronze": 7},
    {"country": "South Korea", "total_medals": 20, "gold": 6, "silver": 4, "bronze": 10},
    {"country": "Poland", "total_medals": 14, "gold": 4, "silver": 5, "bronze": 5},
    {"country": "Czech Republic", "total_medals": 11, "gold": 4, "silver": 4, "bronze": 3},
    {"country": "Kenya", "total_medals": 10, "gold": 4, "silver": 4, "bronze": 2},
    {"country": "Norway", "total_medals": 8, "gold": 4, "silver": 2, "bronze": 2},
    {"country": "Jamaica", "total_medals": 9, "gold": 4, "silver": 1, "bronze": 4},
    {"country": "Spain", "total_medals": 17, "gold": 3, "silver": 8, "bronze": 6},
    {"country": "Sweden", "total_medals": 9, "gold": 3, "silver": 6, "bronze": 0},
    {"country": "Switzerland", "total_medals": 13, "gold": 3, "silver": 4, "bronze": 6},
    {"country": "Denmark", "total_medals": 11, "gold": 3, "silver": 4, "bronze": 4},
    {"country": "Croatia", "total_medals": 8, "gold": 3, "silver": 3, "bronze": 2},
    {"country": "Iran", "total_medals": 7, "gold": 3, "silver": 2, "bronze": 2},
    {"country": "Serbia", "total_medals": 9, "gold": 3, "silver": 1, "bronze": 5},
    {"country": "Belgium", "total_medals": 7, "gold": 3, "silver": 1, "bronze": 3},
    {"country": "Bulgaria", "total_medals": 6, "gold": 3, "silver": 1, "bronze": 2},
    {"country": "Slovenia", "total_medals": 5, "gold": 3, "silver": 1, "bronze": 1},
    {"country": "Uzbekistan", "total_medals": 5, "gold": 3, "silver": 0, "bronze": 2},
    {"country": "Georgia", "total_medals": 8, "gold": 2, "silver": 5, "bronze": 1},
    {"country": "Chinese Taipei", "total_medals": 12, "gold": 2, "silver": 4, "bronze": 6},
    {"country": "Turkey", "total_medals": 13, "gold": 2, "silver": 2, "bronze": 9},
    {"country": "Greece", "total_medals": 4, "gold": 2, "silver": 1, "bronze": 1},
    {"country": "Uganda", "total_medals": 4, "gold": 2, "silver": 1, "bronze": 1},
    {"country": "Ecuador", "total_medals": 3, "gold": 2, "silver": 1, "bronze": 0},
    {"country": "Ireland", "total_medals": 4, "gold": 2, "silver": 0, "bronze": 2},
    {"country": "Israel", "total_medals": 4, "gold": 2, "silver": 0, "bronze": 2},
    {"country": "Qatar", "total_medals": 3, "gold": 2, "silver": 0, "bronze": 1},
    {"country": "Bahamas", "total_medals": 2, "gold": 2, "silver": 0, "bronze": 0},
    {"country": "Kosovo", "total_medals": 2, "gold": 2, "silver": 0, "bronze": 0},
    {"country": "Ukraine", "total_medals": 19, "gold": 1, "silver": 6, "bronze": 12},
    {"country": "Belarus", "total_medals": 7, "gold": 1, "silver": 3, "bronze": 3},
    {"country": "Romania", "total_medals": 4, "gold": 1, "silver": 3, "bronze": 0},
    {"country": "Venezuela", "total_medals": 4, "gold": 1, "silver": 3, "bronze": 0},
    {"country": "India", "total_medals": 7, "gold": 1, "silver": 2, "bronze": 4},
    {"country": "Hong Kong", "total_medals": 6, "gold": 1, "silver": 2, "bronze": 3},
    {"country": "Philippines", "total_medals": 4, "gold": 1, "silver": 2, "bronze": 1},
    {"country": "Slovakia", "total_medals": 4, "gold": 1, "silver": 2, "bronze": 1},
    {"country": "South Africa", "total_medals": 3, "gold": 1, "silver": 2, "bronze": 0},
    {"country": "Austria", "total_medals": 7, "gold": 1, "silver": 1, "bronze": 5},
    {"country": "Egypt", "total_medals": 6, "gold": 1, "silver": 1, "bronze": 4},
    {"country": "Indonesia", "total_medals": 5, "gold": 1, "silver": 1, "bronze": 3},
    {"country": "Ethiopia", "total_medals": 4, "gold": 1, "silver": 1, "bronze": 2},
    {"country": "Portugal", "total_medals": 4, "gold": 1, "silver": 1, "bronze": 2},
    {"country": "Tunisia", "total_medals": 3, "gold": 1}
]  